# Generated by Django 2.0.7 on 2019-07-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default='your post here'),
            preserve_default=False,
        ),
    ]
